/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SwieradowRouteImport } from './routes/swieradow'
import { Route as SosnowkaRouteImport } from './routes/sosnowka'
import { Route as MrzezynoRouteImport } from './routes/mrzezyno'
import { Route as IndexRouteImport } from './routes/index'

const SwieradowRoute = SwieradowRouteImport.update({
  id: '/swieradow',
  path: '/swieradow',
  getParentRoute: () => rootRouteImport,
} as any)
const SosnowkaRoute = SosnowkaRouteImport.update({
  id: '/sosnowka',
  path: '/sosnowka',
  getParentRoute: () => rootRouteImport,
} as any)
const MrzezynoRoute = MrzezynoRouteImport.update({
  id: '/mrzezyno',
  path: '/mrzezyno',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mrzezyno': typeof MrzezynoRoute
  '/sosnowka': typeof SosnowkaRoute
  '/swieradow': typeof SwieradowRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mrzezyno': typeof MrzezynoRoute
  '/sosnowka': typeof SosnowkaRoute
  '/swieradow': typeof SwieradowRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mrzezyno': typeof MrzezynoRoute
  '/sosnowka': typeof SosnowkaRoute
  '/swieradow': typeof SwieradowRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/mrzezyno' | '/sosnowka' | '/swieradow'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/mrzezyno' | '/sosnowka' | '/swieradow'
  id: '__root__' | '/' | '/mrzezyno' | '/sosnowka' | '/swieradow'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MrzezynoRoute: typeof MrzezynoRoute
  SosnowkaRoute: typeof SosnowkaRoute
  SwieradowRoute: typeof SwieradowRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/swieradow': {
      id: '/swieradow'
      path: '/swieradow'
      fullPath: '/swieradow'
      preLoaderRoute: typeof SwieradowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sosnowka': {
      id: '/sosnowka'
      path: '/sosnowka'
      fullPath: '/sosnowka'
      preLoaderRoute: typeof SosnowkaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mrzezyno': {
      id: '/mrzezyno'
      path: '/mrzezyno'
      fullPath: '/mrzezyno'
      preLoaderRoute: typeof MrzezynoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MrzezynoRoute: MrzezynoRoute,
  SosnowkaRoute: SosnowkaRoute,
  SwieradowRoute: SwieradowRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
