/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SwieradowRouteImport } from './routes/swieradow'
import { Route as SosnowkaRouteImport } from './routes/sosnowka'
import { Route as PolitykaPrywatnosciRouteImport } from './routes/polityka-prywatnosci'
import { Route as PolitykaCookiesRouteImport } from './routes/polityka-cookies'
import { Route as MrzezynoRouteImport } from './routes/mrzezyno'
import { Route as IndexRouteImport } from './routes/index'

const SwieradowRoute = SwieradowRouteImport.update({
  id: '/swieradow',
  path: '/swieradow',
  getParentRoute: () => rootRouteImport,
} as any)
const SosnowkaRoute = SosnowkaRouteImport.update({
  id: '/sosnowka',
  path: '/sosnowka',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitykaPrywatnosciRoute = PolitykaPrywatnosciRouteImport.update({
  id: '/polityka-prywatnosci',
  path: '/polityka-prywatnosci',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitykaCookiesRoute = PolitykaCookiesRouteImport.update({
  id: '/polityka-cookies',
  path: '/polityka-cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const MrzezynoRoute = MrzezynoRouteImport.update({
  id: '/mrzezyno',
  path: '/mrzezyno',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mrzezyno': typeof MrzezynoRoute
  '/polityka-cookies': typeof PolitykaCookiesRoute
  '/polityka-prywatnosci': typeof PolitykaPrywatnosciRoute
  '/sosnowka': typeof SosnowkaRoute
  '/swieradow': typeof SwieradowRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mrzezyno': typeof MrzezynoRoute
  '/polityka-cookies': typeof PolitykaCookiesRoute
  '/polityka-prywatnosci': typeof PolitykaPrywatnosciRoute
  '/sosnowka': typeof SosnowkaRoute
  '/swieradow': typeof SwieradowRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mrzezyno': typeof MrzezynoRoute
  '/polityka-cookies': typeof PolitykaCookiesRoute
  '/polityka-prywatnosci': typeof PolitykaPrywatnosciRoute
  '/sosnowka': typeof SosnowkaRoute
  '/swieradow': typeof SwieradowRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mrzezyno'
    | '/polityka-cookies'
    | '/polityka-prywatnosci'
    | '/sosnowka'
    | '/swieradow'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mrzezyno'
    | '/polityka-cookies'
    | '/polityka-prywatnosci'
    | '/sosnowka'
    | '/swieradow'
  id:
    | '__root__'
    | '/'
    | '/mrzezyno'
    | '/polityka-cookies'
    | '/polityka-prywatnosci'
    | '/sosnowka'
    | '/swieradow'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MrzezynoRoute: typeof MrzezynoRoute
  PolitykaCookiesRoute: typeof PolitykaCookiesRoute
  PolitykaPrywatnosciRoute: typeof PolitykaPrywatnosciRoute
  SosnowkaRoute: typeof SosnowkaRoute
  SwieradowRoute: typeof SwieradowRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/swieradow': {
      id: '/swieradow'
      path: '/swieradow'
      fullPath: '/swieradow'
      preLoaderRoute: typeof SwieradowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sosnowka': {
      id: '/sosnowka'
      path: '/sosnowka'
      fullPath: '/sosnowka'
      preLoaderRoute: typeof SosnowkaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/polityka-prywatnosci': {
      id: '/polityka-prywatnosci'
      path: '/polityka-prywatnosci'
      fullPath: '/polityka-prywatnosci'
      preLoaderRoute: typeof PolitykaPrywatnosciRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/polityka-cookies': {
      id: '/polityka-cookies'
      path: '/polityka-cookies'
      fullPath: '/polityka-cookies'
      preLoaderRoute: typeof PolitykaCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mrzezyno': {
      id: '/mrzezyno'
      path: '/mrzezyno'
      fullPath: '/mrzezyno'
      preLoaderRoute: typeof MrzezynoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MrzezynoRoute: MrzezynoRoute,
  PolitykaCookiesRoute: PolitykaCookiesRoute,
  PolitykaPrywatnosciRoute: PolitykaPrywatnosciRoute,
  SosnowkaRoute: SosnowkaRoute,
  SwieradowRoute: SwieradowRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
